CREATE DATABASE K23CNT3_HaQuangMinh_2310900067_Db

CREATE TABLE HQM_QUAN_TRI (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_TaiKhoan NVARCHAR(50) NOT NULL,
    hqm_MatKhau NVARCHAR(255) NOT NULL,
    hqm_TrangThai BIT NOT NULL
);
CREATE TABLE HQM_KHACH_HANG (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_MaKhachHang NVARCHAR(50),
    hqm_HoTenKhachHang NVARCHAR(255) NOT NULL,
    hqm_Email NVARCHAR(255),
    hqm_MatKhau NVARCHAR(255) NOT NULL,
    hqm_DienThoai NVARCHAR(50),
    hqm_DiaChi NVARCHAR(255),
    hqm_NgayDangKy DATE NOT NULL DEFAULT GETDATE(),
    hqm_TrangThai BIT NOT NULL
)
CREATE TABLE HQM_LOAI_SAN_PHAM (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_MaLoai NVARCHAR(50),
    hqm_TenLoai NVARCHAR(255) NOT NULL,
    hqm_TrangThai BIT NOT NULL
);
CREATE TABLE HQM_SAN_PHAM (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_MaSanPham NVARCHAR(50) NOT NULL,
    hqm_TenSanPham NVARCHAR(255) NOT NULL,
    hqm_HinhAnh NVARCHAR(255),
    hqm_SoLuong INT NOT NULL,
    hqm_DonGia FLOAT NOT NULL,
    hqm_MaLoai INT NOT NULL,
    hqm_TrangThai BIT NOT NULL,
    FOREIGN KEY (hqm_MaLoai) REFERENCES HQM_LOAI_SAN_PHAM(id)
);
CREATE TABLE HQM_HOA_DON (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_MaHoaDon NVARCHAR(50) NOT NULL,
    hqm_MaKhachHang INT NOT NULL,
    hqm_NgayHoaDon DATE NOT NULL DEFAULT GETDATE(),
    hqm_Email NVARCHAR(255),
    hqm_DienThoai NVARCHAR(50),
    hqm_DiaChi NVARCHAR(255),
    hqm_TongTriGia FLOAT NOT NULL,
    hqm_TrangThai BIT NOT NULL,
    FOREIGN KEY (hqm_MaKhachHang) REFERENCES HQM_KHACH_HANG(id)
);
CREATE TABLE HQM_CT_HOA_DON (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_HoaDonID INT NOT NULL,
    hqm_SanPhamID INT NOT NULL,
    hqm_SoLuongMua INT NOT NULL,
    hqm_DonGiaMua FLOAT NOT NULL,
    hqm_ThanhTien FLOAT NOT NULL,
    hqm_TrangThai BIT NOT NULL,
    FOREIGN KEY (hqm_HoaDonID) REFERENCES HQM_HOA_DON(id),
    FOREIGN KEY (hqm_SanPhamID) REFERENCES HQM_SAN_PHAM(id)
);
CREATE TABLE HQM_TIN_TUC (
    id INT PRIMARY KEY IDENTITY(1,1),
    hqm_MaTT NVARCHAR(50) NOT NULL,
    hqm_TieuDe NVARCHAR(255) NOT NULL,
    hqm_MoTa NVARCHAR(255),
    hqm_NoiDung NVARCHAR(MAX),
    hqm_NgayDangTin DATE NOT NULL DEFAULT GETDATE(),
    hqm_NgayCapNhat DATE,
    hqm_HinhAnh NVARCHAR(255),
    hqm_TrangThai BIT NOT NULL
);
ALTER TABLE HQM_HOA_DON
ADD CONSTRAINT FK_HoaDon_KhachHang
FOREIGN KEY (hqm_MaKhachHang) REFERENCES HQM_KHACH_HANG(id);
ALTER TABLE HQM_CT_HOA_DON
ADD CONSTRAINT FK_CTHoaDon_HoaDon
FOREIGN KEY (hqm_HoaDonID) REFERENCES HQM_HOA_DON(id);

ALTER TABLE HQM_CT_HOA_DON
ADD CONSTRAINT FK_CTHoaDon_SanPham
FOREIGN KEY (hqm_SanPhamID) REFERENCES HQM_SAN_PHAM(id);
ALTER TABLE HQM_SAN_PHAM
ADD CONSTRAINT FK_SanPham_LoaiSanPham
FOREIGN KEY (hqm_MaLoai) REFERENCES HQM_LOAI_SAN_PHAM(id);